services:
  - type: web
    name: my-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app  # or gunicorn mysite.wsgi:application for Django
    build:
      environment:
        pythonVersion: 3.11.9
