"""Column Added

Revision ID: 409ae46f9576
Revises: a1f01a49c334
Create Date: 2024-06-28 22:37:20.663527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '409ae46f9576'
down_revision: Union[str, None] = 'a1f01a49c334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('teeth', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'teeth')
    # ### end Alembic commands ###
